name: github actions test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check environment
        run: |
          printenv | grep GIT
          git branch --show-current
          git branch
